#!/bin/bash

# AJOUTE UNE PERSONNE DANS LE CARNET dates.txt AU FORMAT PRENOM;NOM;DDN
# variables prenom, nom, ddn, destFile
# nb: une phase de pré-traitement doit avoir lieu pour identifier les variables facilement:

person=$(echo "$1" | tr '_' ' ')
path=$2
db="dates/csv"
destFile="${path}/$db"

if [[ "$#" -ne "2" ]]; then # PARAMETERS
	echo "Usage : $0 prenom;nom;ddn path"
	exit 1
else
	nbLinesBefore=$(wc -l ${destFile} | cut -d ' ' -f 1)
	isAlreadyInDB=$(grep -i "$person" "$destFile" | wc -l)

	if [[ "$isAlreadyInDB" -eq "1" ]]; then
		echo "Cette personne est déjà répertoriée dans la base de données"
		exit 1
	fi

	echo ${person} >> ${destFile}
	nbLinesAfter=$(wc -l ${destFile} | cut -d ' ' -f 1)
	
	# vérification que la ligne a bien été ajoutée dans la BDD
	if [ "${nbLinesBefore}" != "${nbLinesAfter}" ]; then
		exit 0 # success
	else
		exit 1 # failure
	fi
fi
