#!/bin/bash
	#cherche les anniversaires du jour + permet de trouver la DDN de qqn de la liste.
	#permet également d'ajouter des personnes à la liste d'anniversaire

path=$(cat env)


# Initialisation des couleurs
setup_colors() {
	if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
		NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
	else
		NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
	fi
}

# Méthode qui gère les affichages en couleur. à appeler au lieu de "echo"
msg() {
  echo >&2 -e "${1-}"
}

leave() {
	msg "${PURPLE}À bientôt!${NOFORMAT}"
}

# Affiche le jour en cours et cherche un anniversaire sur le jour en cours
# Un message spécifie s'il y a ou non un anniversaire, et si oui donne les noms et âges des personnes concernées.


# Affichage du menu
menu() {
	msg "${BLUE}1)${NOFORMAT}Prenom    ${BLUE}2)${NOFORMAT}Nom    ${BLUE}3)${NOFORMAT}Date de Naissance    ${BLUE}4)${NOFORMAT}Ajout    ${BLUE}5)${NOFORMAT}Quitter"
}

# Affiche un message d'erreur lorsqu'un nom ou un prénom ne sont pas trouvés lors d'une recherche
msgNotFound(){
	arg=$1
	msg "${RED}Personne n'a été trouvé sous ce ${arg}. Veuillez vérifier la casse.${NOFORMAT}"
}

msgIncorrectValue() {
	msg "${RED}Valeur incorrecte${NOFORMAT}"
}

msgAddFailed() {
	msg "${RED}Echec de l'ajout de l'individu. Veuillez réessayer.${NOFORMAT}"
}

# Méthode principale. Gère l'ensemble des méthodes
main() {
	path=$1
	msg "${BLUE}Chercher${NOFORMAT}"

	while [ "$sortie" != "true" ]		#AFFICHAGE MENU
	do

		menu
		msg "Quel choix? (entrer le ${BLUE}nombre${NOFORMAT})"
		read choix

		case $choix in					#MENU
			1)					#RECHERCHE PAR PRENOM
			read -p "Entrer le prénom : " prenom
			if [[ "$(${path}/cherche selectPrenom ${prenom} ${path} | wc -l)" -ge "1" ]]; then	#SI AU MOINS UN RESULTAT TROUVE
				msg "${CYAN}"
				${path}/cherche selectPrenom $prenom $path
				msg "${NOFORMAT}"
			else
				msgNotFound "prénom"
			fi
			;;
			
			2)				# RECHERCHE PAR NOM
			read -p "Entrer le nom : " nom
			if [[ "$(${path}/cherche selectNom ${nom} ${path} | wc -l)" -ge "1" ]]; then
				msg "${CYAN}"
				${path}/cherche selectNom $nom ${path}
				msg "${NOFORMAT}"				
			else
				msgNotFound "nom"
			fi
			;;
			
			3)				# RECHERCHE PAR DDN
			echo "Entrer la date de naissance au format 'jj/mm/aaaa' (ou jj/mm ou bien une fraction de ce format) : " 
			read ddn
			if [[ "$(${path}/cherche selectAll ${ddn} ${path} | wc -l)" -ge "1" ]]; then
				msg "${CYAN}"
				${path}/cherche selectAll $ddn ${path}
				msg "${NOFORMAT}"
			else
				echo "Personne n'a été trouvé sous cette date de naissance."
			fi
			;;
			
			4) #AJOUTER
			echo "Entrer le nom de famille de la personne à ajouter : "
			read nom1 nom2 nom3 nom4 nom5
			
			if [[ ! -z ${nom5} ]]; then
				nom1="${nom1}_${nom2}_${nom3}_${nom4}_${nom5}"
			elif [[ ! -z ${nom4} ]]; then
				nom1="${nom1}_${nom2}_${nom3}_${nom4}"
			elif [[ ! -z ${nom3} ]]; then
				nom1="${nom1}_${nom2}_${nom3}"
			elif [[ ! -z ${nom2} ]]; then
				nom1="${nom1}_${nom2}"		
			fi
			echo "Entrer le prénom de la personne à ajouter : "
			read prenom1 prenom2
			if [[ ! -z ${prenom2} ]]; then
				prenom1="${prenom1}_${prenom2}"		
			fi
			echo "Entrer la date de naissance de la personne à ajouter (format jj/mm/aaaa)"
			read ddn
			# CONCATENATION DES NOMS ET/OU PRENOMS COMPOSÉS AVEC DES '_' POUR UN TRANSFERT FACILITÉ DES PARAMÈTRES
			${path}/ajoute "${prenom1};${nom1};${ddn}" "${path}"
			if [[ "$?" -eq "0" ]]; then #succès
				msg "${GREEN}${prenom1} ${nom1} ajouté avec succès!${NOFORMAT}"
			else
				msgAddFailed
			fi
			;;
			
			5) #QUITTER	
			sortie="true"
			;;
			
			*)
			msgIncorrectValue
			;;
			
		esac
	done

	leave

	exit
}

#----------------------------
setup_colors
./dailyCheck ${path}
main ${path}
